export const SESSION_UIDKUDOU = 'SESSION_UIDKUDOU';
export const STORE_TOKENKUDOU="STORE_TOKENKUDOU";
export const STORE_USERINFOKUDOU="STORE_USERINFOKUDOU";
export const STORE_INDEXDATAKUDOU="STORE_INDEXDATAKUDOU";
export const STORE_LOG_OUT="STORE_LOG_OUT";